### ISSUE TITLE
Add a push to hub method

### ISSUE THREAD

**Issue by davanstrien** [AnswerDotAI/fastdata#3]
Very nice to see more synthetic data generation tools. Would be nice to have a method to push generated data to the Hugging Face Hub.

Happy to open a pr if it's of interest 🤗

**Comment by ncoop57** [comment]
Sure, I think it would also be a good idea to save/push every XX amount of generations to prevent lost work. Would appreciate a PR to tackle this!

**Comment by Wauplin** [comment]
Hey there, maintainer of `huggingface_hub` here :hugs: For iterative backups, we have the `huggingface_hub.CommitScheduler` that should do exactly what you want (i.e. "please upload this folder every X minutes"). You can check out this guide for more details: https://huggingface.co/docs/huggingface_hub/guides/upload#scheduled-uploads. In order to make a proper integration, `fastdata` would need to: 1. have a way to save data to disk while it's generated (currently only outputted in `.generate`) 2. generate a basic dataset card to explain how the dataset has been created and how to use it 3. integrate `CommitScheduler` for regular commits.

**Comment by ncoop57** [comment]
Sick, thanks for the help with how to best integrate with the 🤗 hub @Wauplin ! @davanstrien wanna give a PR a shot on getting this integrated? 🤓

**Comment by AndreaFrancis** [comment]
Hi @ncoop57, I opened https://github.com/AnswerDotAI/fastdata/pull/9 to push generated data to the HF hub. I would be glad to receive your comments/feedback.

**Comment by ncoop57** [comment]
Closing thanks to the awesome PR from @AndreaFrancis 🔥
