### ISSUE TITLE
api_key isn't supported

### ISSUE THREAD

**Issue by nattaylor** [AnswerDotAI/fastdata#4]
README.md says you can pass an `api_key` argument, but it is not implemented.

This is easily worked around with the environment variable.

**Comment by ncoop57** [comment]
Thanks for the issue @nattaylor ! Is there a specific usecase you image where the person would require passing it as a variable rather than having it as an environment variable that we automatically read? I'm down to add support for it though we will need to do it in 2 places, one here, and one in our claudette library.

**Comment by nattaylor** [comment]
The docs say the `api_key` arg is supported and it's the first thing I tried ...that's my only use case.  It was trivially resolved by setting the env variable, so I agree that my PR is dumb.

>We only support Anthropic models at the moment. Therefore, make sure you have an API key for the model you want to use and the proper environment variables set or pass the api key to the [FastData](https://answerdotai.github.io/fastdata/core.html#fastdata) class FastData(api_key="sk-ant-api03-...").
